{{- if eq .Values.postgresql.enabled true -}}
{{- if not .Values.postgresql.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql.name" . }}
  labels:
    app: {{ template "lxp-skill-service.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  username: {{ .Values.postgresql.username | b64enc | quote }}
  password: {{ .Values.postgresql.password | b64enc | quote }}
  database: {{ .Values.postgresql.database | b64enc | quote }}
{{- end -}}
{{- end -}}
