# Generated by Django 3.0.9 on 2020-08-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmodel',
            name='slug',
            field=models.SlugField(max_length=64, verbose_name='Skill slug'),
        ),
    ]
