# Generated by Django 3.0.9 on 2020-08-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_app', '0002_auto_20200813_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmodel',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Skill name'),
        ),
        migrations.AlterField(
            model_name='skillmodel',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='Skill slug'),
        ),
    ]
