# Generated by Django 3.0.9 on 2020-08-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_app', '0003_auto_20200818_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrometheusModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
            ],
            options={
                'db_table': 'prometheus',
            },
        ),
    ]
